# Generated by Django 4.1.1 on 2022-09-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingrequest",
            name="geoip",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="incomingrequest",
            name="ipinfo",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="incomingrequest",
            name="ipware",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="incomingrequest",
            name="latitude",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="incomingrequest",
            name="longitude",
            field=models.FloatField(blank=True, max_length=40, null=True),
        ),
    ]
