# Generated by Django 4.1.1 on 2022-09-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_created_incomingrequest_dated_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incomingrequest",
            old_name="dated",
            new_name="track_date",
        ),
    ]
